basePath: /
definitions:
  base.BaseResponse:
    properties:
      data:
        description: Response data for success
      error_data:
        description: Detailed error data for failure
      message:
        type: string
      status:
        type: boolean
    type: object
  entities.Article:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      photo:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  entities.User:
    properties:
      address:
        type: string
      email:
        type: string
      id_user:
        type: integer
      name:
        type: string
      nik:
        type: string
      password:
        type: string
      phone_number:
        type: string
      role:
        type: string
      token:
        type: string
    type: object
  request.ArticleRequest:
    description: ArticleRequest is the request for the Article endpoint
    properties:
      content:
        type: string
      photo:
        type: string
      title:
        type: string
    type: object
  request.CommentRequest:
    description: CommentRequest is the request for the Comment endpoint
    properties:
      article_id:
        type: integer
      comment:
        type: string
      user_id:
        type: integer
    type: object
  request.LikeRequest:
    description: LikeRequest is the request for the Like endpoint
    properties:
      article_id:
        type: integer
      user_id:
        type: integer
    type: object
  request.LoginRequest:
    description: LoginRequest is the request for the login endpoint
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.RegisterRequest:
    description: RegisterRequest is the request for the register endpoint
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  response.ArticleResponse:
    description: ArticleResponse is the response for the Article controller
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      photo:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  response.CommentResponse:
    description: CommentResponse is the response for the Comment controller
    properties:
      article:
        $ref: '#/definitions/entities.Article'
      comment:
        type: string
      created_at:
        type: string
      id:
        type: integer
      user:
        $ref: '#/definitions/entities.User'
    type: object
  response.CountLikesResponse:
    properties:
      article_id:
        type: integer
      count:
        type: integer
    type: object
  response.IsLikedResponse:
    properties:
      article_id:
        type: integer
      is_liked:
        type: boolean
      user_id:
        type: integer
    type: object
  response.LikeResponse:
    properties:
      Article:
        $ref: '#/definitions/entities.Article'
      User:
        $ref: '#/definitions/entities.User'
      article_id:
        type: integer
      id:
        type: integer
      user_id:
        type: integer
    type: object
  response.LoginResponse:
    description: LoginResponse is the response for the Login controller
    properties:
      email:
        type: string
      id:
        type: integer
      nama:
        type: string
      token:
        type: string
    type: object
  response.RegisterResponse:
    description: RegisterResponse is the response for the Register controller
    properties:
      email:
        type: string
      id:
        type: integer
      nama:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is the API documentation for Lokajatim.
  title: Lokajatim API
  version: "1.0"
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: Get all articles
      parameters:
      - description: Article Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ArticleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Get all articles
      tags:
      - Article
    post:
      consumes:
      - application/json
      description: Create article
      parameters:
      - description: Article Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ArticleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.ArticleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Create article
      tags:
      - Article
  /articles/{id}:
    delete:
      consumes:
      - application/json
      description: Delete article
      parameters:
      - description: ID of the article
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Delete article
      tags:
      - Article
    get:
      consumes:
      - application/json
      description: Get article by ID
      parameters:
      - description: ID of the article
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ArticleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Get article by ID
      tags:
      - Article
    put:
      consumes:
      - application/json
      description: Update article
      parameters:
      - description: ID of the article
        in: path
        name: id
        required: true
        type: integer
      - description: Article Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.ArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ArticleResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Update article
      tags:
      - Article
  /comments:
    post:
      consumes:
      - application/json
      description: Create comment
      parameters:
      - description: Comment Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CommentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.CommentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Create comment
      tags:
      - Comment
  /comments/{id}:
    delete:
      consumes:
      - application/json
      description: Delete comment
      parameters:
      - description: ID of the comment
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Delete comment
      tags:
      - Comment
    get:
      consumes:
      - application/json
      description: Get comment by ID
      parameters:
      - description: ID of the comment
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Get comment by ID
      tags:
      - Comment
  /comments/article/{article_id}:
    get:
      consumes:
      - application/json
      description: Get comments by article ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommentResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Get comments by article ID
      tags:
      - Comment
  /likes:
    post:
      consumes:
      - application/json
      parameters:
      - description: Like Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LikeRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.LikeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Like an article
      tags:
      - Likes
  /likes/{article_id}/{user_id}:
    delete:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/base.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Unlike an article
      tags:
      - Likes
  /likes/{article_id}/users/{user_id}/status:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.IsLikedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Check if a user liked an article
      tags:
      - Likes
  /likes/articles/{article_id}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.LikeResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Get all likes for an article
      tags:
      - Likes
  /likes/articles/{article_id}/count:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CountLikesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Count likes for an article
      tags:
      - Likes
  /login:
    post:
      consumes:
      - application/json
      description: User login endpoint
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Login
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: User registration endpoint
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/base.BaseResponse'
      summary: Register
      tags:
      - Auth
swagger: "2.0"
